[package]
edition = { workspace = true }
license = { workspace = true }
name = "usc-abi-encoding"
publish = true
version = "0.5.0"
description = "Ethereum ABI encoding library. Used for the encoding of transactions and proof submission in the Creditcoin USC network."

[dependencies]
alloy = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
hex = { version = "0.4" }
