[package]
edition = { workspace = true }
license = { workspace = true }
name = "usc-query-builder"
publish = true
version = "0.8.0"
description = "Query builder library. Used for the construction of USC proving queries."

[dependencies]
alloy = { workspace = true }
alloy-json-abi = { workspace = true, features = ["serde_json"] }
async-trait = { version = "0.1" }
hex = { workspace = true }

usc-abi-encoding = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
